[theme]
base="light"
primaryColor="#0068C9" # Um azul moderno
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#0F1116"
font="sans serif"
layout="wide"

[server]
runOnSave = true
